import type { RouteDef, TicketDef, RouteColor } from './map.js';

/** Ticket to Ride — Europe-style map: 47 cities, 68 single routes. */

export const EUROPE_CITY_POS: Record<string, [number, number]> = {
  edinburgh: [18, 5], london: [22, 14], amsterdam: [30, 12], bruxelles: [27, 18],
  dieppe: [22, 20], paris: [26, 25], brest: [15, 23], pamplona: [18, 38],
  madrid: [14, 46], lisboa: [7, 49], cadiz: [11, 55], barcelona: [20, 47],
  marseille: [30, 40], zurich: [33, 30], frankfurt: [34, 20], essen: [36, 14],
  berlin: [43, 14], munchen: [39, 25], venezia: [39, 33], roma: [40, 44],
  palermo: [44, 56], brindisi: [48, 48], wien: [45, 24], zagreb: [45, 33],
  budapest: [50, 27], sarajevo: [51, 39], athina: [56, 53], sofia: [56, 43],
  bucuresti: [61, 34], kobenhavn: [39, 7], stockholm: [46, 3], danzig: [49, 9],
  warszawa: [52, 16], riga: [54, 6], wilno: [59, 13], petrograd: [66, 3],
  moskva: [70, 10], smolensk: [64, 16], kyiv: [62, 22], kharkov: [70, 21],
  rostov: [76, 25], sevastopol: [70, 33], sochi: [78, 32], constantinople: [64, 45],
  angora: [73, 46], smyrna: [63, 53], erzurum: [82, 43],
};

function r(a: string, b: string, length: number, color: RouteColor): RouteDef {
  return { id: `${a}~${b}`, a, b, length, color };
}

export const EUROPE_ROUTES: RouteDef[] = [
  r('edinburgh', 'london', 4, 'black'),
  r('london', 'amsterdam', 2, 'gray'),
  r('london', 'dieppe', 2, 'gray'),
  r('dieppe', 'brest', 2, 'orange'),
  r('dieppe', 'paris', 1, 'purple'),
  r('dieppe', 'bruxelles', 2, 'green'),
  r('bruxelles', 'amsterdam', 1, 'black'),
  r('bruxelles', 'paris', 2, 'yellow'),
  r('bruxelles', 'frankfurt', 2, 'blue'),
  r('amsterdam', 'essen', 3, 'yellow'),
  r('amsterdam', 'frankfurt', 2, 'white'),
  r('brest', 'paris', 3, 'black'),
  r('brest', 'pamplona', 4, 'purple'),
  r('paris', 'frankfurt', 3, 'white'),
  r('paris', 'pamplona', 4, 'blue'),
  r('paris', 'marseille', 4, 'gray'),
  r('pamplona', 'madrid', 3, 'black'),
  r('pamplona', 'barcelona', 2, 'gray'),
  r('pamplona', 'marseille', 4, 'red'),
  r('madrid', 'lisboa', 3, 'purple'),
  r('madrid', 'cadiz', 3, 'orange'),
  r('madrid', 'barcelona', 2, 'yellow'),
  r('lisboa', 'cadiz', 2, 'blue'),
  r('barcelona', 'marseille', 4, 'gray'),
  r('marseille', 'zurich', 2, 'purple'),
  r('marseille', 'roma', 4, 'gray'),
  r('zurich', 'paris', 3, 'gray'),
  r('zurich', 'munchen', 2, 'yellow'),
  r('zurich', 'venezia', 2, 'green'),
  r('frankfurt', 'essen', 2, 'green'),
  r('frankfurt', 'munchen', 2, 'purple'),
  r('frankfurt', 'berlin', 3, 'red'),
  r('essen', 'berlin', 2, 'blue'),
  r('essen', 'kobenhavn', 3, 'gray'),
  r('berlin', 'danzig', 4, 'gray'),
  r('berlin', 'warszawa', 4, 'purple'),
  r('berlin', 'wien', 3, 'green'),
  r('munchen', 'wien', 3, 'orange'),
  r('munchen', 'venezia', 2, 'blue'),
  r('venezia', 'roma', 2, 'black'),
  r('venezia', 'zagreb', 2, 'gray'),
  r('roma', 'palermo', 4, 'gray'),
  r('roma', 'brindisi', 2, 'white'),
  r('palermo', 'brindisi', 3, 'gray'),
  r('palermo', 'smyrna', 6, 'gray'),
  r('brindisi', 'athina', 4, 'gray'),
  r('zagreb', 'wien', 2, 'gray'),
  r('zagreb', 'sarajevo', 3, 'red'),
  r('zagreb', 'budapest', 2, 'orange'),
  r('wien', 'budapest', 1, 'red'),
  r('wien', 'warszawa', 4, 'blue'),
  r('budapest', 'sarajevo', 3, 'purple'),
  r('budapest', 'bucuresti', 4, 'white'),
  r('sarajevo', 'sofia', 2, 'gray'),
  r('sarajevo', 'athina', 4, 'green'),
  r('athina', 'smyrna', 2, 'gray'),
  r('sofia', 'bucuresti', 2, 'gray'),
  r('sofia', 'constantinople', 3, 'blue'),
  r('bucuresti', 'constantinople', 3, 'yellow'),
  r('bucuresti', 'kyiv', 4, 'gray'),
  r('bucuresti', 'sevastopol', 4, 'white'),
  r('constantinople', 'smyrna', 2, 'gray'),
  r('constantinople', 'angora', 2, 'gray'),
  r('constantinople', 'sevastopol', 4, 'gray'),
  r('angora', 'smyrna', 3, 'orange'),
  r('angora', 'erzurum', 3, 'black'),
  r('erzurum', 'sochi', 3, 'red'),
  r('erzurum', 'sevastopol', 4, 'gray'),
  r('sochi', 'sevastopol', 2, 'gray'),
  r('sochi', 'rostov', 2, 'gray'),
  r('sevastopol', 'rostov', 4, 'gray'),
  r('rostov', 'kharkov', 2, 'green'),
  r('kharkov', 'kyiv', 4, 'gray'),
  r('kharkov', 'moskva', 4, 'gray'),
  r('kyiv', 'warszawa', 4, 'gray'),
  r('kyiv', 'wilno', 2, 'gray'),
  r('kyiv', 'smolensk', 3, 'red'),
  r('smolensk', 'moskva', 2, 'orange'),
  r('smolensk', 'wilno', 3, 'yellow'),
  r('moskva', 'petrograd', 4, 'white'),
  r('petrograd', 'wilno', 4, 'blue'),
  r('petrograd', 'riga', 4, 'gray'),
  r('riga', 'wilno', 4, 'green'),
  r('riga', 'danzig', 3, 'black'),
  r('danzig', 'warszawa', 2, 'gray'),
  r('warszawa', 'wilno', 3, 'red'),
  r('kobenhavn', 'stockholm', 3, 'yellow'),
  r('stockholm', 'petrograd', 6, 'gray'),
];

export const EUROPE_TICKETS: TicketDef[] = [
  { a: 'lisboa', b: 'danzig', points: 20 },
  { a: 'brest', b: 'petrograd', points: 20 },
  { a: 'palermo', b: 'moskva', points: 20 },
  { a: 'kobenhavn', b: 'erzurum', points: 21 },
  { a: 'edinburgh', b: 'athina', points: 21 },
  { a: 'cadiz', b: 'stockholm', points: 13 },
  { a: 'london', b: 'wien', points: 10 },
  { a: 'london', b: 'berlin', points: 7 },
  { a: 'amsterdam', b: 'pamplona', points: 7 },
  { a: 'amsterdam', b: 'wilno', points: 12 },
  { a: 'frankfurt', b: 'kobenhavn', points: 5 },
  { a: 'frankfurt', b: 'smolensk', points: 13 },
  { a: 'paris', b: 'wien', points: 8 },
  { a: 'paris', b: 'zagreb', points: 7 },
  { a: 'madrid', b: 'dieppe', points: 8 },
  { a: 'madrid', b: 'zurich', points: 8 },
  { a: 'barcelona', b: 'bruxelles', points: 8 },
  { a: 'barcelona', b: 'munchen', points: 8 },
  { a: 'marseille', b: 'essen', points: 8 },
  { a: 'roma', b: 'smyrna', points: 8 },
  { a: 'venezia', b: 'constantinople', points: 10 },
  { a: 'berlin', b: 'bucuresti', points: 8 },
  { a: 'berlin', b: 'moskva', points: 12 },
  { a: 'budapest', b: 'sofia', points: 5 },
  { a: 'athina', b: 'angora', points: 5 },
  { a: 'athina', b: 'wilno', points: 11 },
  { a: 'warszawa', b: 'smolensk', points: 6 },
  { a: 'kyiv', b: 'petrograd', points: 6 },
  { a: 'kyiv', b: 'sochi', points: 8 },
  { a: 'riga', b: 'bucuresti', points: 10 },
  { a: 'zurich', b: 'brindisi', points: 6 },
  { a: 'zurich', b: 'budapest', points: 6 },
];
