/** Drawable prompts — a mix of easy objects and trickier concepts. */
export const PICTIONARY_WORDS: string[] = [
  'airplane', 'anchor', 'angel', 'ant', 'apple', 'arrow', 'astronaut', 'avalanche',
  'backpack', 'balloon', 'banana', 'baseball', 'basket', 'bat', 'beach', 'bear',
  'bed', 'bee', 'bell', 'bicycle', 'birthday cake', 'blanket', 'boat', 'bone',
  'book', 'bowtie', 'bridge', 'broom', 'bubble', 'bus', 'butterfly', 'cactus',
  'camel', 'camera', 'campfire', 'candle', 'castle', 'caterpillar', 'cheese', 'chef',
  'cherry', 'church', 'circus', 'cloud', 'clown', 'compass', 'cookie', 'cowboy',
  'crab', 'crayon', 'crocodile', 'crown', 'cupcake', 'dentist', 'desert', 'diamond',
  'dinosaur', 'dolphin', 'door', 'dragon', 'dream', 'drum', 'duck', 'eagle',
  'earthquake', 'egg', 'elephant', 'envelope', 'eyebrow', 'feather', 'fence', 'firefighter',
  'fireworks', 'fishing', 'flag', 'flashlight', 'flower', 'football', 'forest', 'fountain',
  'frog', 'ghost', 'giraffe', 'glasses', 'glove', 'grapes', 'guitar', 'hamburger',
  'hammer', 'hammock', 'headphones', 'helicopter', 'hedgehog', 'honey', 'horse', 'hospital',
  'hot air balloon', 'ice cream', 'igloo', 'island', 'jellyfish', 'juggler', 'kangaroo', 'key',
  'kite', 'knight', 'ladder', 'ladybug', 'lawnmower', 'lighthouse', 'lightning', 'lion',
  'lipstick', 'lobster', 'magician', 'mailbox', 'mermaid', 'microphone', 'moon', 'mosquito',
  'mountain', 'moustache', 'mushroom', 'ninja', 'ocean', 'octopus', 'owl', 'paintbrush',
  'pajamas', 'pancake', 'parachute', 'peacock', 'penguin', 'piano', 'picnic', 'pillow',
  'pineapple', 'pirate', 'pizza', 'popcorn', 'pyramid', 'rainbow', 'robot', 'rocket',
  'roller coaster', 'sandcastle', 'sandwich', 'saxophone', 'scarecrow', 'scissors', 'shark', 'skateboard',
  'sledgehammer', 'snail', 'snowman', 'spaceship', 'spider', 'squirrel', 'stairs', 'strawberry',
  'submarine', 'sunflower', 'sunglasses', 'surfboard', 'swing', 'sword', 'telescope', 'tent',
  'tornado', 'tractor', 'treasure', 'trophy', 'turtle', 'umbrella', 'unicorn', 'vacuum',
  'volcano', 'waffle', 'waterfall', 'watermelon', 'whale', 'wheelchair', 'windmill', 'wizard',
  'yo-yo', 'zebra', 'zipper', 'zombie',
];
